/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Saree = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isNewArrival' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'occasion' : IDL.Text,
  'price' : IDL.Float64,
  'isOffer' : IDL.Bool,
  'fabric' : IDL.Text,
});

export const idlService = IDL.Service({
  'addSaree' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text, IDL.Text, IDL.Bool, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'getAllSarees' : IDL.Func([], [IDL.Vec(Saree)], ['query']),
  'getNewArrivals' : IDL.Func([], [IDL.Vec(Saree)], ['query']),
  'getOffers' : IDL.Func([], [IDL.Vec(Saree)], ['query']),
  'getSaree' : IDL.Func([IDL.Nat], [Saree], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Saree = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isNewArrival' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'occasion' : IDL.Text,
    'price' : IDL.Float64,
    'isOffer' : IDL.Bool,
    'fabric' : IDL.Text,
  });
  
  return IDL.Service({
    'addSaree' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'getAllSarees' : IDL.Func([], [IDL.Vec(Saree)], ['query']),
    'getNewArrivals' : IDL.Func([], [IDL.Vec(Saree)], ['query']),
    'getOffers' : IDL.Func([], [IDL.Vec(Saree)], ['query']),
    'getSaree' : IDL.Func([IDL.Nat], [Saree], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };