/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Saree {
  'id' : bigint,
  'name' : string,
  'isNewArrival' : boolean,
  'imageUrl' : string,
  'occasion' : string,
  'price' : number,
  'isOffer' : boolean,
  'fabric' : string,
}
export interface _SERVICE {
  'addSaree' : ActorMethod<
    [string, string, number, string, string, boolean, boolean],
    bigint
  >,
  'getAllSarees' : ActorMethod<[], Array<Saree>>,
  'getNewArrivals' : ActorMethod<[], Array<Saree>>,
  'getOffers' : ActorMethod<[], Array<Saree>>,
  'getSaree' : ActorMethod<[bigint], Saree>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];